[project]
name = "jrnl"
dynamic = ["version"]
description = "Make notes of activities easily"
readme = "README.md"
authors = [
    { name = "Daniel Engval", email = "daniel@engvalls.eu" }
]
requires-python = ">=3.13"
dependencies = [
    "cffi==1.17.1",
    "colorama==0.4.6",
    "cryptography==45.0.6",
    "cyclopts>=3.22.5",
    "dateparser>=1.2.2",
    "jaraco-classes==3.4.0",
    "jaraco-context==6.0.1",
    "jaraco-functools==4.3.0",
    "keyring==25.6.0",
    "loguru>=0.7.3",
    "markdown-it-py==4.0.0",
    "matplotlib>=3.10.6",
    "mdurl==0.1.2",
    "more-itertools==10.7.0",
    "nicegui>=2.23.0",
    "notebook>=7.4.5",
    "ollama>=0.5.3",
    "pandas>=2.3.2",
    "parsedatetime==2.6",
    "persist-cache>=0.4.4",
    "platformdirs>=4.4.0",
    "pycparser==2.22",
    "pygments==2.19.2",
    "python-dateutil==2.9.0.post0",
    "pywebview>=6.0",
    "pyxdg==0.28",
    "rich==14.1.0",
    "ruamel-yaml==0.18.15",
    "ruamel-yaml-clib==0.2.12",
    "shared-memory-dict>=0.7.2",
    "six==1.17.0",
    "tabulate>=0.9.0",
    "tzlocal==5.3.1",
    "xkcd>=2.4.2",
]

[project.scripts]
jrnl = "jrnl.main:run"
jrnl-cli = "jrnl.tasks.cli:main"

[build-system]
requires = ["hatchling>=1.26"]
build-backend = "hatchling.build"

[tool.hatch.version]
# Point this to the file that defines __version__ (adjust path to your package)
path = "src/jrnl/__version__.py"

[dependency-groups]
dev = [
    "wat>=0.7.0",
]
